version: "3.5"
services:
  musicroom-database:
    image: mysql:8.0
    container_name: musicroom-database
    ports:
      - "3308:3306"
    networks: ["musicroom"]
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: musicroom # 사용자 생성
      MYSQL_PASSWORD: qwe123Yt # 사용자 비밀번호
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./initdb/01-grant-permissions.sql:/docker-entrypoint-initdb.d/01-grant-permissions.sql
      - ./initdb/musicroom.sql:/docker-entrypoint-initdb.d/musicroom.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

networks:
  musicroom:
    name: musicroom

volumes:
  mariadb_data:
